version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:17"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    groups:
      python-runtime-dependencies:
        dependency-type: "production"
      python-dev-dependencies:
        dependency-type: "development"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:37"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"
